import { Database } from '@/types/supabase';

type Profile = Database['public']['Tables']['profiles']['Row'] & {
    media?: Database['public']['Tables']['media']['Row'][];
};

export const MOCK_PROFILES: any[] = [
    {
        id: 'mock-1',
        display_name: 'Isabella',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 23,
        height: '1.65m',
        weight: '55kg',
        city: 'São Paulo',
        state: 'SP',
        telegram: 'isabellaluxo',
        instagram: 'isabella.luxo',
        twitter: 'isabellax',
        neighborhood: 'Jardins', // Added
        price: 300,
        is_online: true,
        verified: true,
        rating: 4.9,
        reviews_count: 124,
        services: ['Massagem Relaxante', 'Namoradinha', 'Jantar', 'Viagens', 'Fetiches', 'Beijo na boca', 'Oral até o final'],
        description: 'Olá amores, sou a Isabella. Uma companheira elegante, divertida e muito carinhosa. Adoro conhecer pessoas novas e proporcionar momentos inesquecíveis. Falo inglês e português.',
        hairColor: 'Morena',
        bodyType: 'Magro',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX', 'Cartão de Crédito'],
        hasPlace: true,
        videoCall: true,
        media: [
            { id: '1', profile_id: 'mock-1', url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80', type: 'image', created_at: '' },
            { id: '1b', profile_id: 'mock-1', url: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=800&q=80', type: 'image', created_at: '' },
            { id: '1v', profile_id: 'mock-1', url: '', type: 'video', created_at: '' }
        ]
    },
    {
        id: 'mock-2',
        display_name: 'Sophie',
        role: 'advertiser',
        gender: 'trans',
        category: 'Massagista', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 21,
        height: '1.70m',
        weight: '58kg',
        city: 'Rio de Janeiro',
        state: 'RJ',
        telegram: 'sophiesensual',
        instagram: 'sophie.rio',
        twitter: 'sophiex',
        neighborhood: 'Copacabana', // Added
        price: 250,
        is_online: false,
        verified: true,
        rating: 4.8,
        reviews_count: 89,
        services: ['Massagem Tântrica', 'Iniciantes', 'Casais', 'Oral com camisinha'],
        description: 'Sophie, a sua melhor escolha no Rio. Doce, menina mulher, pronta para realizar suas fantasias mais ocultas com total discrição.',
        hairColor: 'Loira',
        bodyType: 'Mignon',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: false,
        videoCall: true,
        media: [
            { id: '2', profile_id: 'mock-2', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80', type: 'image', created_at: '' },
            { id: '2b', profile_id: 'mock-2', url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', type: 'image', created_at: '' }
        ]
    },
    {
        id: 'mock-3',
        display_name: 'Valentina',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 25,
        height: '1.68m',
        weight: '60kg',
        city: 'Curitiba',
        state: 'PR',
        telegram: 'valentinadom',
        instagram: 'valentina.curitiba',
        twitter: 'valentinadmx',
        neighborhood: 'Batel', // Added
        price: 400,
        is_online: true,
        verified: true,
        rating: 5.0,
        reviews_count: 42,
        services: ['Dominatrix', 'Fetiches Pesados', 'Roleplay', 'Sado suave'],
        description: 'Valentina. Atitude e beleza em um só pacote. Se você procura algo fora do comum, acabou de encontrar.',
        hairColor: 'Ruiva',
        bodyType: 'Curvilínea',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX', 'Crypto'],
        hasPlace: true,
        videoCall: false,
        media: [
            { id: '3', profile_id: 'mock-3', url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', type: 'image', created_at: '' },
            { id: '3v', profile_id: 'mock-3', url: '', type: 'video', created_at: '' }
        ]
    },
    {
        id: 'mock-4',
        display_name: 'Gabriela',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 19,
        height: '1.60m',
        weight: '50kg',
        city: 'Belo Horizonte',
        state: 'MG',
        telegram: 'gabibh',
        instagram: 'gabi.massagem',
        twitter: '',
        neighborhood: 'Savassi', // Added
        price: 200,
        is_online: false,
        verified: false,
        rating: 4.7,
        reviews_count: 15,
        services: ['Massagem', 'Oral', 'Completo', 'Ejaculação corpo'],
        description: 'Gabriela, a mineinha que você sempre sonhou. Carinhosa e safada na medida certa.',
        hairColor: 'Morena',
        bodyType: 'Mignon',
        ethnicity: 'Mulata',
        paymentMethods: ['Dinheiro'],
        hasPlace: false,
        videoCall: true,
        media: [{ id: '4', profile_id: 'mock-4', url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-5',
        display_name: 'Fernanda',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 28,
        height: '1.75m',
        weight: '65kg',
        city: 'Porto Alegre',
        state: 'RS',
        telegram: 'fernandapoa',
        instagram: 'fer.class',
        twitter: 'ferluxury',
        neighborhood: 'Moinhos de Vento', // Added
        price: 350,
        is_online: true,
        verified: true,
        rating: 4.9,
        reviews_count: 210,
        services: ['Acompanhante de Luxo', 'Jantares', 'Eventos', 'Namoradinha'],
        description: 'Fernanda. Classe e sofisticação para homens de bom gosto.',
        hairColor: 'Loira',
        bodyType: 'Fitness',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX', 'Cartão de Crédito'],
        hasPlace: true,
        videoCall: false,
        media: [{ id: '5', profile_id: 'mock-5', url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-6',
        display_name: 'Julia',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 22,
        height: '1.67m',
        weight: '56kg',
        city: 'Salvador',
        state: 'BA',
        telegram: 'juliabahia',
        instagram: 'ju.ssalvador',
        twitter: '',
        neighborhood: 'Barra', // Added
        price: 150,
        is_online: true,
        verified: false,
        rating: 4.5,
        reviews_count: 56,
        services: ['Massagem', 'Relaxamento', 'Oral com camisinha'],
        description: 'Julia. A alegria e o calor da Bahia com você.',
        hairColor: 'Morena',
        bodyType: 'Curvilínea',
        ethnicity: 'Negra',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: true,
        media: [{ id: '6', profile_id: 'mock-6', url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-7',
        display_name: 'Camila',
        role: 'advertiser',
        gender: 'trans',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 24,
        height: '1.72m',
        weight: '62kg',
        city: 'Brasília',
        state: 'DF',
        telegram: 'camiladf',
        instagram: 'camilatrans',
        twitter: 'camilax',
        neighborhood: 'Asa Sul', // Added
        price: 500,
        is_online: false,
        verified: true,
        rating: 5.0,
        reviews_count: 31,
        services: ['Executivos', 'Discrição Total', 'Viagens'],
        description: 'Camila. O segredo mais bem guardado de Brasília.',
        hairColor: 'Preto',
        bodyType: 'Magro',
        ethnicity: 'Oriental',
        paymentMethods: ['Dinheiro', 'PIX', 'Crypto'],
        hasPlace: false,
        videoCall: false,
        media: [{ id: '7', profile_id: 'mock-7', url: 'https://images.unsplash.com/photo-1554151228-14d9def656ec?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-8',
        display_name: 'Larissa',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 20,
        height: '1.63m',
        weight: '52kg',
        city: 'Fortaleza',
        state: 'CE',
        telegram: '',
        instagram: 'larissa.praia',
        twitter: '',
        neighborhood: 'Meireles', // Added
        price: 200,
        is_online: true,
        verified: true,
        rating: 4.6,
        reviews_count: 78,
        services: ['Namoradinha', 'Praia', 'Diversão', 'Beijo na boca'],
        description: 'Larissa. Venha curtir o sol e o mar comigo.',
        hairColor: 'Loira',
        bodyType: 'Fitness',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: true,
        media: [{ id: '8', profile_id: 'mock-8', url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-9',
        display_name: 'Gabriel',
        role: 'advertiser',
        gender: 'homem',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 26,
        height: '1.80m',
        weight: '80kg',
        city: 'São Paulo',
        state: 'SP',
        telegram: 'gabrielsp',
        instagram: 'gabriel.boy',
        twitter: 'gabrielx',
        neighborhood: 'Pinheiros', // Added
        price: 300,
        is_online: true,
        verified: true,
        rating: 4.8,
        reviews_count: 12,
        services: ['Acompanhante', 'Massagem', 'Casais'],
        description: 'Gabriel, discreto e educado, pronto para te servir.',
        hairColor: 'Moreno',
        bodyType: 'Atlético',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: false,
        media: [{ id: '9', profile_id: 'mock-9', url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80', type: 'image', created_at: '' }]
    }
];
